name: Bug Report
description: Report broken or incorrect behavior
labels: ["unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill ot a bug.
        If yo want real-time support, consider joining or [Discord server](https://discord.gg/gJDbCw8aQy) instead.

        Please note that this form is for bugs only!
  - type: input
    attributes:
      label: Summary
      description: A simple summary of yor bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What yo did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: >
        A short snippet of code that showcases the bug.
      render: python
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did yo expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Intents
      description: >
        What intents are yo using for yor bot?
        This is the `disnake.Intents` class yo pass to the client.
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Information
      description: >
        Run `python -m disnake -v` and paste the otput below.

        If yo are unable to run this command, show some basic information involving
        yor system such as operating system and Python version.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure yo've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
